export default {
  COUNTRIES_REQUEST: "COUNTRIES_REQUEST",
  COUNTRIES_REQUEST_SUCCESS: "COUNTRIES_REQUEST_SUCCESS",
  COUNTRIES_REQUEST_FAILURE: "COUNTRIES_REQUEST_FAILURE",
  COUNTRIES_SET_ALL_COUNTRIES: "COUNTRIES_SET_ALL_COUNTRIES",
  COUNTRIES_SET_FAVORITE_COUNTRY: "COUNTRIES_SET_FAVORITE_COUNTRY",
  COUNTRIES_REMOVE_FAVORITE_COUNTRY: "COUNTRIES_REMOVE_FAVORITE_COUNTRY",
  COUNTRIES_SET_CURRENT_COUNTRY: "COUNTRIES_SET_CURRENT_COUNTRY",

  COUNTRIES_GET_ALL_COUNTRIES_SAGA: "COUNTRIES_GET_ALL_COUNTRIES_SAGA",
  COUNTRIES_GET_UNIQUE_COUNTRY_SAGA: "COUNTRIES_GET_UNIQUE_COUNTRY_SAGA",
  COUNTRIES_GET_LIST_COUNTRIES_SAGA: "COUNTRIES_GET_LIST_COUNTRIES_SAGA",
};
