export default {
  EVENT_REQUEST: "EVENT_REQUEST",
  EVENT_POST_REQUEST: "EVENT_POST_REQUEST",
  EVENT_GET_BY_HASH_REQUEST: "EVENT_GET_BY_HASH_REQUEST",
  EVENT_DELETE_REQUEST: "EVENT_DELETE_REQUEST",

  EVENT_REQUEST_SUCCESS: "EVENT_REQUEST_SUCCESS",
  EVENT_REQUEST_FAILURE: "EVENT_REQUEST_FAILURE",
  EVENT_CLEAR_DATA: "EVENT_CLEAR_DATA",
};
