-- MySQL Script

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `yobetit` DEFAULT CHARACTER SET utf8mb4 ;
USE `yobetit` ;

-- Table `yobetit`.`CASINO`
CREATE TABLE IF NOT EXISTS `yobetit`.`CASINO` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `NAME` VARCHAR(128) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
);

-- Table `yobetit`.`GAME`
CREATE TABLE IF NOT EXISTS `yobetit`.`GAME` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `NAME` VARCHAR(128) NOT NULL,
  `TYPE` VARCHAR(64) NOT NULL UNIQUE,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
   INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
   INDEX `TYPE_UNIQUE` (`TYPE` ASC) VISIBLE
);

-- Table `yobetit`.`CASINO_GAME`
CREATE TABLE IF NOT EXISTS `yobetit`.`CASINO_GAME` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `FK_CASINO_CASINO_GAME` INT NOT NULL,
  `FK_GAME_CASINO_GAME` INT NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `FK_CASINO_CASINO_GAME_idx` (`FK_CASINO_CASINO_GAME` ASC) VISIBLE,
  INDEX `FK_GAME_CASINO_GAME_idx` (`FK_GAME_CASINO_GAME` ASC) VISIBLE,
  CONSTRAINT `FK_CASINO_CASINO_GAME`
    FOREIGN KEY (`FK_CASINO_CASINO_GAME`)
    REFERENCES `yobetit`.`CASINO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GAME_CASINO_GAME`
    FOREIGN KEY (`FK_GAME_CASINO_GAME`)
    REFERENCES `yobetit`.`GAME` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- Table `yobetit`.`COUNTRY`
CREATE TABLE IF NOT EXISTS `yobetit`.`COUNTRY` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `NAME` VARCHAR(45) UNIQUE NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE
);

-- Table `yobetit`.`COUNTRY_GAME`
CREATE TABLE IF NOT EXISTS `yobetit`.`COUNTRY_GAME` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `FK_GAME_COUNTRY_GAME` INT NOT NULL,
  `FK_COUNTRY_COUNTRY_GAME` INT NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `FK_GAME_COUNTRY_GAME_idx` (`FK_GAME_COUNTRY_GAME` ASC) VISIBLE,
  INDEX `FK_COUNTRY_COUNTRY_GAME_idx` (`FK_COUNTRY_COUNTRY_GAME` ASC) VISIBLE,
  CONSTRAINT `FK_GAME_COUNTRY_GAME`
    FOREIGN KEY (`FK_GAME_COUNTRY_GAME`)
    REFERENCES `yobetit`.`GAME` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COUNTRY_COUNTRY_GAME`
    FOREIGN KEY (`FK_COUNTRY_COUNTRY_GAME`)
    REFERENCES `yobetit`.`COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- Table `yobetit`.`PLAYER`
CREATE TABLE IF NOT EXISTS `yobetit`.`PLAYER` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(128) UNIQUE NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `FK_COUNTRY_PLAYER` INT NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  INDEX `FK_COUNTRY_PLAYER_idx` (`FK_COUNTRY_PLAYER` ASC) VISIBLE,
  CONSTRAINT `FK_COUNTRY_PLAYER`
    FOREIGN KEY (`FK_COUNTRY_PLAYER`)
    REFERENCES `yobetit`.`COUNTRY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- Table `yobetit`.`PLAYER_GAME_FAVORITE`
CREATE TABLE IF NOT EXISTS `yobetit`.`PLAYER_GAME_FAV` (
  `ID` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  `FK_GAME_PLAYER_GAME_FAV` INT NOT NULL,
  `FK_PLAYER_PLAYER_GAME_FAV` INT NOT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETED_AT` DATETIME NULL DEFAULT NULL,
  INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_GAME_PLAYER_GAME_FAV_idx` (`FK_GAME_PLAYER_GAME_FAV` ASC) VISIBLE,
  INDEX `FK_PLAYER_PLAYER_GAME_FAV_idx` (`FK_PLAYER_PLAYER_GAME_FAV` ASC) VISIBLE,
  CONSTRAINT `FK_GAME_PLAYER_GAME_FAV`
    FOREIGN KEY (`FK_GAME_PLAYER_GAME_FAV`)
    REFERENCES `yobetit`.`GAME` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAYER_PLAYER_GAME_FAV`
    FOREIGN KEY (`FK_PLAYER_PLAYER_GAME_FAV`)
    REFERENCES `yobetit`.`PLAYER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
