INSERT INTO `yobetit`.`CASINO` (`NAME`) VALUES ('Bellagio');
INSERT INTO `yobetit`.`CASINO` (`NAME`) VALUES ('Monte Carlo');
INSERT INTO `yobetit`.`CASINO` (`NAME`) VALUES ('Di Venecia');

INSERT INTO `yobetit`.`GAME` (`NAME`, `TYPE`) VALUES ('Slot Machine', 'Slot');
INSERT INTO `yobetit`.`GAME` (`NAME`, `TYPE`) VALUES ('Roulette', 'Roulette');
INSERT INTO `yobetit`.`GAME` (`NAME`, `TYPE`) VALUES ('Blackjack', 'Card');
INSERT INTO `yobetit`.`GAME` (`NAME`, `TYPE`) VALUES ('Video Poker', 'Poker');

INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('Brazil');
INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('Poland');
INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('Malta');
INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('United States of America');
INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('Italy');
INSERT INTO `yobetit`.`COUNTRY` (`NAME`) VALUES ('Argentina');

INSERT INTO `yobetit`.`PLAYER` (`NAME`, `EMAIL`, `PASSWORD`, `FK_COUNTRY_PLAYER`) VALUES ('Guilherme Vecino', 'guilherme.vecino@gmail.com', '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08', '1');
INSERT INTO `yobetit`.`PLAYER` (`NAME`, `EMAIL`, `PASSWORD`, `FK_COUNTRY_PLAYER`) VALUES ('Carlos Delgado', 'carlos.delgado@fake.com', '1b4f0e9851971998e732078544c96b36c3d01cedf7caa332359d6f1d83567014', '6');
INSERT INTO `yobetit`.`PLAYER` (`NAME`, `EMAIL`, `PASSWORD`, `FK_COUNTRY_PLAYER`) VALUES ('Giuseppe Conte', 'giuseppe.conte@fake.com', '60303ae22b998861bce3b28f33eec1be758a213c86c93c076dbe9f558c11c752', '5');
INSERT INTO `yobetit`.`PLAYER` (`NAME`, `EMAIL`, `PASSWORD`, `FK_COUNTRY_PLAYER`) VALUES ('Otto Sobieslaw', 'otto.sobieslaw@fake.com', 'fd61a03af4f77d870fc21e05e7e80678095c92d808cfb3b5c279ee04c74aca13', '2');
INSERT INTO `yobetit`.`PLAYER` (`NAME`, `EMAIL`, `PASSWORD`, `FK_COUNTRY_PLAYER`) VALUES ('John Doe', 'john.doe@fake.com', '91d3510c0672508f97b00f917e513e4dc2f57dd6e53cab95c28eebdc3f88a108', '4');

INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('1', '1');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('1', '2');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('1', '3');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('1', '4');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('2', '3');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('2', '4');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('3', '1');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('3', '2');
INSERT INTO `yobetit`.`CASINO_GAME` (`FK_CASINO_CASINO_GAME`, `FK_GAME_CASINO_GAME`) VALUES ('3', '3');

INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('1', '1');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('3', '1');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('5', '1');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('2', '2');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('3', '2');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('4', '2');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('1', '3');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('3', '3');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('3', '4');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('2', '4');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('4', '4');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('3', '5');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('1', '5');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('1', '6');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('2', '6');
INSERT INTO `yobetit`.`COUNTRY_GAME` (`FK_GAME_COUNTRY_GAME`, `FK_COUNTRY_COUNTRY_GAME`) VALUES ('4', '6');

INSERT INTO `yobetit`.`PLAYER_GAME_FAV` (`FK_GAME_PLAYER_GAME_FAV`, `FK_PLAYER_PLAYER_GAME_FAV`) VALUES ('1', '1');
INSERT INTO `yobetit`.`PLAYER_GAME_FAV` (`FK_GAME_PLAYER_GAME_FAV`, `FK_PLAYER_PLAYER_GAME_FAV`) VALUES ('2', '1');
INSERT INTO `yobetit`.`PLAYER_GAME_FAV` (`FK_GAME_PLAYER_GAME_FAV`, `FK_PLAYER_PLAYER_GAME_FAV`) VALUES ('1', '5');
INSERT INTO `yobetit`.`PLAYER_GAME_FAV` (`FK_GAME_PLAYER_GAME_FAV`, `FK_PLAYER_PLAYER_GAME_FAV`) VALUES ('3', '5');
