USE `yobetit`;
SELECT P.* FROM PLAYER as P
  INNER JOIN PLAYER_GAME_FAV as PGF ON P.ID = PGF.FK_PLAYER_PLAYER_GAME_FAV
  INNER JOIN GAME as G ON G.ID = PGF.FK_GAME_PLAYER_GAME_FAV WHERE G.TYPE = "Slot"